//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using WpfApp1.Classes;
using System.Linq;

namespace WpfApp1.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int BookId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> MaxDiscountId { get; set; }
        public Nullable<int> MakerId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> ActiveDiscountId { get; set; }
        public Nullable<int> Count { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    
        public virtual ActiveDiscount ActiveDiscount { get; set; }
        public virtual Category Category { get; set; }
        public virtual Maker Maker { get; set; }
        public virtual MaxDiscount MaxDiscount { get; set; }
        public virtual Supplier Supplier { get; set; }
        public string NewPrice
        {
            get
            {
                if (ActiveDiscountId != null)
                {
                    string a = Convert.ToString(Price - (Price / 100 * DatabaseConnectionClass.DatabaseConnection.ActiveDiscount.Where(c => c.ActiveDiscountId == ActiveDiscountId).First().Value));
                    return "\t" + a;
                }
                else return null;
            }
        }
    }
}
